### PR TITLE
Add extra dependencies.

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

When I tried to build a recipe for dsc, it failed because it was missing xxhash. This PR updates the sos recipe to include the extra dependencies defined in [extras_require](https://github.com/vatlab/SoS/blob/master/setup.py#L204).

### CODE REVIEW

**Review by gaow — COMMENTED** [review]
For SoS to display DAG after execution we also need the executable `dot` which on Linux is part of `graphviz` package. Should this be an extra dependency? Notice that SoS works perfectly fine without it. It becomes problematic only when users require plotting DAG into the HTML report and we do properly throw an error message and quit in that scenario. Not sure if we should make `graphviz` (whatever package containing `dot`) a dependency too in this [meta.yaml](https://github.com/conda-forge/sos-feedstock/pull/1/commits/1bbaba5d3941f83b3d91da2f65d042d4d6f3dd46) @BoPeng ?

**Comment by BoPeng** [comment]
`graphviz` (for `dot` to convert `.dot` to `.png`) and `imagemagick` (to manipulate `png` into animation) are required for the display of DAG as animations. We list `graphviz` and `imagemagick` as extra requirements because they can be tricky to set up. The fact that `imagemagick` has evolved to version 7 but its python binding only works for version 6 had caused us a lot of trouble. So unless we are sure that the conda dependencies work with sos, we should not include them.

**Comment by jdblischak** [comment]
> For SoS to display DAG after execution we also need the executable dot which on Linux is part of graphviz package. Should this be an extra dependency?

@gaow That's part of what this PR is doing. By adding python-graphviz as a dependency, the command-line utility graphviz is installed because it's a dependency of that package: https://github.com/conda-forge/python-graphviz-feedstock/blob/master/recipe/meta.yaml#L27

> So unless we are sure that the conda dependencies work with sos, we should not include them.

@BoPeng I agree we only want to include them if they work.

@gaow In your [DSC installation instructions](https://stephenslab.github.io/dsc-wiki/installation.html), you recommend installing graphviz and imageio from conda. Are these conda packages able to visualize the DAG successfully?

**Comment by gaow** [comment]
@jdblischak those packages were only meant to setup a complete SoS environment; in DSC calls to SoS routines those packages are not involved. I do not think I put in those conda instructions (or recommend them) -- I always relied in `pip` which can install `python-graphviz` and `imageio` but I'm sure pip does not take care of `dot`. 

Good to know this problem is taken care of in `conda` automatically. I guess it is one other benefit using `conda`  over `pip`.

**Comment by jdblischak** [comment]
> I do not think I put in those conda instructions (or recommend them)

@gaow I see that Peter wrote [a lot of the installation instructions](https://github.com/stephenslab/dsc-wiki/blame/master/installation/index.ipynb). I understand if you don't follow these exact ones yourself, but you should recommend them if they are the official instructions! :-) Once dsc is on conda-forge, I'll send a PR to simplify the instructions.

> Good to know this problem is taken care of in conda automatically. I guess it is one other benefit using conda over pip.

Exactly. This is one of the biggest features of conda for me. `pip` and `install.packages()` can't install system dependencies.

**Comment by jdblischak** [comment]
@BoPeng What about xxhash? Are you ok with adding it as a dependency? conda-forge doesn't build packages for win32, so I think it should be safe to install it as part of the conda package.

**Comment by BoPeng** [comment]
We do not require `xxhash` on windows, but it can use it if it is available. The problem with windows is that most users do not have a compiler so it has to install the binary version of `xxhash`, which is not readily available through `pip`. If `conda-forge` does not build for win32, we can list it safely.

**Comment by jdblischak** [comment]
@BoPeng OK. I've updated the PR to only add xxhash. I don't have time right now to properly test the visualization features using the versions available from conda-forge. I can always add them later.

Please let me know if you approve (either comment here or by approving the PR via the GitHub mechanism).

**Comment by BoPeng** [comment]
The tricky question is: if we list imagemagick and graphiviz there, will they be installed automatically, even though they may not work correctly for sos? The bottom line is that `sos` should be installed and runnable so I am fine either way.

**Comment by jdblischak** [comment]
> The tricky question is: if we list imagemagick and graphiviz there, will they be installed automatically, even though they may not work correctly for sos?

@BoPeng Right, they would be automatically installed even if they weren't useful. That's why I am excluding them until I know that they would improve the SoS experience for a conda-forge user.

**Pull request merged**
